### ISSUE TITLE
SqsPoller do not handle task cancellation correctly

### ISSUE THREAD

**Issue by IhnatKlimchuk** [AlexeyBogdan95/SqsPoller#48]
Please take a look at next test:
https://github.com/IhnatKlimchuk/SqsPoller/blob/playground/test/SqsPoller.Tests.Unit/ConsumerResolverTests.cs#L184

Task cancelled this way causes `ContinueWith` task see `task.IsCancelled == true` but still deleting message from sqs.
example of consumer https://github.com/IhnatKlimchuk/SqsPoller/blob/playground/test/SqsPoller.Tests.Unit/ThrowingMessageConsumer.cs#L14

same issue is reproduced while stopping host

This issue is pretty important as caused some data loss on prod envs.

**Comment by AlexeyBogdan95** [comment]
Hi @IhnatKlimchuk. https://github.com/AlexeyBogdan95/SqsPoller/pull/50 fixes the issue.
