### ISSUE TITLE
SqsPoller do not have any limitation on messages consumed as result causing timeouts 

### ISSUE THREAD

**Issue by IhnatKlimchuk** [AlexeyBogdan95/SqsPoller#49]
Please see https://github.com/IhnatKlimchuk/SqsPoller/tree/playground/test/SqsPoller.LoadTest for more details. 

SqsPoller tries to read all available messages. In case of huge amount of messages that leads to:
- OOM 
- Timeouts on http calls if so exist in consumer (due to local queue LIFO in task scheduler, limited connection pool, bottleneck in consumer)  
- unplanned degradation on other parts of service (api calls in case service has such)

**Comment by AlexeyBogdan95** [comment]
Hi @IhnatKlimchuk. Seems that last versions fix the issue. Can we close it?

**Comment by IhnatKlimchuk** [comment]
Yes we can close this issue
