### ISSUE TITLE
Add ability to set default log level on message handling error

### ISSUE THREAD

**Issue by IhnatKlimchuk** [AlexeyBogdan95/SqsPoller#68]
```
private async Task ProcessEvent(Message message, CancellationToken cancellationToken, SemaphoreSlim semaphore, string queueUrl)
        {
            try
            {
                await _consumerResolver.Resolve(message, cancellationToken);
                DeleteMessage(queueUrl, message, cancellationToken);
            }
            catch (OperationCanceledException e)
            {
                _logger.LogWarning(e,
                    "Failed to handle message with id {message_id} and ReceiptHandle {receipt_handle}. Task has been cancelled");
            }
            catch (Exception e)
            {
                _logger.LogError(e,
                    "Failed to handle message with id {message_id} and ReceiptHandle {receipt_handle}");
            }
            finally
            {
                semaphore.Release();
            }
        }
```

Error during handling can be resulted by race condition and/or similar issue. Issue will cause retry by SQS, but you can't avoid `Error` logs, otherwise message will be assumed "consumed" correctly.

Add ability for one of
- set log level on message handling error
- pass consumption `result` to avoid deleting message
- custom SqlPoller `exception` for "Warning" level similar to `OperationCanceledException `

**Comment by dsharkou** [comment]
@IhnatKlimchuk Could you please prepare PR with the fix, unit test? I'll approve & merge it

**Comment by AlexeyBogdan95** [comment]
Hi @IhnatKlimchuk. I will take a look. Thanks.

**Comment by AlexeyBogdan95** [comment]
Hi guys @IhnatKlimchuk @dsharkou. Could you please take a look at the PR above^^?
Please let me know if anything else should be added as a part of these issue.
Thanks.

**Comment by AlexeyBogdan95** [comment]
FYI
https://www.nuget.org/packages/SqsPoller/1.1.0-prerelease-20220512202532 contains PR updates.

**Comment by dsharkou** [comment]
Merged and published - https://www.nuget.org/packages/SqsPoller/1.1.0
